### ISSUE TITLE
trojan与测试版caddy会出现panic

### ISSUE THREAD

**Issue by text01001** [imgk/caddy-trojan#59]
不好意识又要打扰大佬了，经过测试
由 caddy commit：https://github.com/caddyserver/caddy/commit/bbe1952a59a196b7598c6488beb770ec38a70dfc 加 trojan commit：https://github.com/imgk/caddy-trojan/commit/8be66197156d46c0a4f7562f6c9656f4e0c13906 编译出来的caddy版本：
```
/tmp/caddy/caddy version
v2.7.0-beta.2.0.20230712203222-bbe1952a59a1 h1:KJUD4kDiKshD0zHBzVY95ELWxluG2ha1Ff2ru8peWp0=
```

启动后会panic
经过精简配置文件，定位到确实是与trojan相关

caddyfile配置：
```
{
	log {
		output file /tmp/caddy/caddy_log.txt
		level INFO
	}
	trojan {
		caddy
		no_proxy
		users pw1234
	}
	servers 127.0.0.1:88 {
		listener_wrappers {
			trojan
		}
	}
}

:88 {
	bind 127.0.0.1
	route {
		reverse_proxy 127.0.0.1:80
	}
}
```

log启动日志：
```
{"level":"warn","ts":1689223101.1303897,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
{"level":"info","ts":1689223101.8108592,"msg":"using provided configuration","config_file":"/tmp/caddy/Caddyfile","config_adapter":""}
{"level":"warn","ts":1689223101.875325,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/tmp/caddy/Caddyfile","line":20}
{"level":"info","ts":1689223101.8815844,"msg":"redirected default logger","from":"stderr","to":"/tmp/caddy/caddy_log.txt"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xfc01ec]

goroutine 1 [running]:
github.com/caddyserver/caddy/v2.Context.AppIfConfigured(...)
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/context.go:444
github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Cleanup(0x3bb1ea0)
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/modules/caddytls/tls.go:335 +0xc0
github.com/caddyserver/caddy/v2.NewContext.func1()
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/context.go:67 +0x1c8
github.com/caddyserver/caddy/v2.run.func1()
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/caddy.go:419 +0x54
github.com/caddyserver/caddy/v2.run(0x3930390, 0x1)
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/caddy.go:484 +0x7c0
github.com/caddyserver/caddy/v2.unsyncedDecodeAndRun({0x391e5a0, 0x1c2, 0x1e0}, 0x1)
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/caddy.go:337 +0x1bc
github.com/caddyserver/caddy/v2.changeConfig({0x1a4299f, 0x4}, {0x1a4af44, 0x7}, {0x391e3c0, 0x1c2, 0x1e0}, {0x0, 0x0}, 0x1)
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/caddy.go:228 +0x94c
github.com/caddyserver/caddy/v2.Load({0x391e3c0, 0x1c2, 0x1e0}, 0x1)
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/caddy.go:127 +0x240
github.com/caddyserver/caddy/v2/cmd.cmdRun({0x38bc780})
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/cmd/commandfuncs.go:222 +0x9d0
github.com/caddyserver/caddy/v2/cmd.WrapCommandFuncForCobra.func1(0x397e900, {0x3c69de0, 0x0, 0x2})
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/cmd/cobra.go:126 +0x60
github.com/spf13/cobra.(*Command).execute(0x397e900, {0x3c69dd0, 0x2, 0x2})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x8a0
github.com/spf13/cobra.(*Command).ExecuteC(0x2b51ee0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x4c0
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/caddyserver/caddy/v2/cmd.Main()
	github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230712203222-bbe1952a59a1/cmd/main.go:64 +0xa8
main.main()
	caddy/main.go:18 +0x38
```

**Comment by imgk** [comment]
从报错看，都没执行到caddy-trojan的代码啊，没有头绪

**Comment by lxhao61** [comment]
j经测试caddy-trojan的master全无效了。使用https://github.com/caddyserver/caddy/commit/7ceef91295343237f5b81ed00e3ba7e8e594d603及之前源码编译出错；使用https://github.com/caddyserver/caddy/commit/7ceef91295343237f5b81ed00e3ba7e8e594d603之后源码编译无问题，但无法启动，报错如上一样。

**Comment by text01001** [comment]
> 经测试caddy-trojan的master分支全无用了。使用Caddy master分支的[7ceef91](https://github.com/caddyserver/caddy/commit/7ceef91295343237f5b81ed00e3ba7e8e594d603)及之前源码编译出错；使用[7ceef91](https://github.com/caddyserver/caddy/commit/7ceef91295343237f5b81ed00e3ba7e8e594d603)之后源码编译无问题，但无法启动，报错如上一样。

lxhao61大佬好，我在caddy那边也反馈了，等待caddy那边修复 https://github.com/caddyserver/caddy/issues/5628

**Comment by lxhao61** [comment]
> > 经测试caddy-trojan的master分支全无用了。使用Caddy master分支的[7ceef91](https://github.com/caddyserver/caddy/commit/7ceef91295343237f5b81ed00e3ba7e8e594d603)及之前源码编译出错；使用[7ceef91](https://github.com/caddyserver/caddy/commit/7ceef91295343237f5b81ed00e3ba7e8e594d603)之后源码编译无问题，但无法启动，报错如上一样。
> 
> lxhao61大佬好，我在caddy那边也反馈了，等待caddy那边修复 [caddyserver/caddy#5628](https://github.com/caddyserver/caddy/issues/5628)

由Caddy修复有点麻烦，问题主要出在这边插件（不启用插件无问题）。若由Caddy修复除非不影响其自己更新及规划，否则其可能不会修复。

**Comment by text01001** [comment]
大佬，caddy那边 (https://github.com/caddyserver/caddy/commit/b51dc5d5d0b8764165170af1f54b77d6de8cb5a1) 已经修了panic问题，但启动trojan插件还是报错无法运行，麻烦看一下是否是trojan插件的问题。
```
{"level":"warn","ts":1689976533.7841501,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
{"level":"info","ts":1689976534.4376004,"msg":"using provided configuration","config_file":"/tmp/caddy/Caddyfile","config_adapter":""}
{"level":"warn","ts":1689976534.4769194,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/tmp/caddy/Caddyfile","line":22}
{"level":"info","ts":1689976534.4823287,"msg":"redirected default logger","from":"stderr","to":"/tmp/caddy/caddy_log.txt"}
Error: loading initial config: loading new config: loading http app module: provision http: loading listener wrapper modules: position 0: loading module 'trojan': provision caddy.listeners.trojan: listener: trojan is not configured
 endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1689976534.4964209,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x3481c20"}
{"level":"info","ts":1689976534.4975605,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0x3481c20"}
```

**Comment by text01001** [comment]
请问下，这个错误是因为什么
```
Error: loading initial config: loading new config: loading http app module: provision http: server srv3: setting up route handlers: route 5: loading handler modules: position 1: loading module 'trojan': provision http.handlers.trojan: handler: trojan is not configured
```

**Comment by text01001** [comment]
经过排查配置文件内容，又发现个问题：
trojan插件里开启ws的话，
```
{
	order trojan before route
	order reverse_proxy before trojan
	admin off
	log {
		output file /tmp/caddy/caddy_log.txt
		level INFO
	}
	trojan {
		caddy
		no_proxy
		users pws1234
	}
	servers :88 {
		listener_wrappers {
			proxy_protocol
			trojan
		}
		protocols h1 h2c
		trusted_proxies cloudflare {
			interval 12h
			timeout 15s
		}
	}
}
:88 {
	bind 127.0.0.1
	trojan {
		connect_method
		websocket
	}
	route {
		reverse_proxy 127.0.0.1:80
	}
}

```

会导致启动失败，报错日志：
```
Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'trojan': provision http.handlers.trojan: handler: trojan is not configured

```

去掉ws支持就能正常启动。
**trojan {
		connect_method
		websocket
	}**

**Comment by text01001** [comment]
~~女马的，caddy真的是瞎折腾。~~
怎么写配置都不能正常用，不是trojan不能用就是reverse_proxy、grpc不能工作。
先退回7月9号二进制了，**就不做了，睡大觉！**
